# Setup
title:               Azimuth Mercantile Goods
tagline:             "by VulcanSmithy"
description:         'A collection of notes.'
url:                 https://azimuthmercantilegoods.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Azimuth Actual
  url:               https://github.com/azimuthmercantilegoods
  email:             azimuth.mercantile.goods@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

